app = "sebo"
primary_region = "gru"

[env]
  PORT = "8000"
  DEBUG = "False"
  DATABASE_URL = "sqlite:///db.sqlite3"
  ALLOWED_HOSTS = "example.fly.dev,example.com"

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
